# Generated by Django 2.2.6 on 2020-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0002_pig_watchdog_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='pig_watchdog_info_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
