# Generated by Django 2.2.5 on 2020-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0003_pig_watchdog_info_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='pig_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pigid', models.CharField(max_length=64)),
                ('Birthdate', models.CharField(max_length=64)),
                ('Weight', models.CharField(max_length=64)),
                ('Fodder', models.CharField(max_length=64)),
                ('Vaccine', models.CharField(max_length=32)),
                ('Disease', models.CharField(max_length=64)),
            ],
        ),
    ]
